### ISSUE TITLE
(Like Scalefast) If the letter "H" is made up of components, there's a traceback

### ISSUE THREAD

**Issue by colinmford** [ohnotypeco/Transmutor-Ext#14]
It can't make measurements because of the components

```
Traceback (most recent call last):
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontParts/base/component.py", line 276, in _drawPoints
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontTools/pens/pointPen.py", line 264, in addComponent
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontTools/pens/basePen.py", line 217, in addComponent
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 1054, in <module>
  File "main.py", line 1050, in main
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 3803, in registerRoboFontSubscriber
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 3482, in addRoboFontSubscriber
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/mojo/subscriber.py", line 1461, in __init__
  File "main.py", line 385, in started
  File "main.py", line 422, in reset
  File "main.py", line 176, in updateScaler
  File "/Users/jamieotelsberg/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/objects/scaler.py", line 69, in __init__
  File "/Users/jamieotelsberg/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/objects/scaler.py", line 178, in addMaster
  File "/Users/jamieotelsberg/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/objects/scaler.py", line 168, in _makeMaster
  File "/Users/jamieotelsberg/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/objects/fonts.py", line 173, in __init__
  File "/Users/jamieotelsberg/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/objects/fonts.py", line 180, in processDimensions
  File "/Users/jamieotelsberg/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 64, in getRefStems
  File "/Users/jamieotelsberg/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/utilities/fontUtils.py", line 252, in getGlyphBox
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontParts/base/glyph.py", line 633, in draw
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontParts/base/component.py", line 251, in draw
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontParts/base/component.py", line 259, in _draw
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontParts/base/component.py", line 265, in drawPoints
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontParts/base/component.py", line 279, in _drawPoints
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontTools/pens/pointPen.py", line 264, in addComponent
  File "/Applications/RoboFont 2.app/Contents/Resources/lib/python3.9/fontTools/pens/basePen.py", line 217, in addComponent
TypeError: 'NoneType' object is not subscriptable
```

**Comment by colinmford** [comment]
This might have been solved by a new version of MutatorScale, need to make sure it gets upstreamed to the repo
