### ISSUE TITLE
Selected Fonts Issue

### ISSUE THREAD

**Issue by connordavenport** [ohnotypeco/Transmutor-Ext#16]
I have been using the updated version and I love having it as an extension now:) I am noticing an issue when working with multiple fonts that aren't in the selection. E.g. I have 10 UFOs open but only using 2 for my interpolation. When I do something that calls the reset function, the UI repopulates and selects everything. I think its this line that is causing the issue but I'm not 100% sure. Should it be `and` so it doesn't just add everything?

https://github.com/ohnotypeco/Transmutor-Ext/blob/497f8f18a4c40d827db274ed2b7ee249330d2b52/Transmutor.roboFontExt/lib/main.py#L418

**Comment by colinmford** [comment]
@connordavenport good to know! There's a lot around that particular part of the UI that needs work, will try to fix

**Comment by ryanbugden** [comment]
I think I'm having a similar issue.

Use case: Working on a Mono Regular. Also have a Proportional Regular and Bold open. Want to only activate the checkbox for the latter two. Clicking back into the Glyph Editor reselects all fonts.

Tracebacks, some of which relevant:

```
Traceback (most recent call last):
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/objects/scaler.py", line 295, in _getInstance
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/mutatorMath/objects/mutator.py", line 38, in buildMutator
TypeError: '<' not supported between instances of 'MathGlyph' and 'MathGlyph'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/vanilla/vanillaEditText.py", line 11, in controlTextDidChange_
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 520, in action_
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/ezui/items/textField.py", line 463, in _internalCallback
  File "main.py", line 650, in glyphNamesTextBoxCallback
  File "main.py", line 462, in redrawView
  File "main.py", line 198, in getScaledGlyph
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/objects/scaler.py", line 262, in getScaledGlyph
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/objects/scaler.py", line 286, in _getInstanceGlyph
  File "/Users/Ryan/Library/Application Support/RoboFont/plugins/Transmutor.roboFontExt/submodules/MutatorScale/lib/mutatorScale/objects/scaler.py", line 300, in _getInstance
AttributeError: 'TypeError' object has no attribute 'message'
/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/fontParts/base/deprecated.py:654: DeprecationWarning: 'Font.selection: use Font.selectedGlyphNames'
Traceback (most recent call last):
  File "/Applications/RoboFont-4_5b2.app/Contents/Resources/lib/python3.9/vanilla/vanillaBase.py", line 520, in action_
  File "main.py", line 734, in addToGlyphButtonCallback
  File "main.py", line 432, in addToGlyph
AttributeError: 'NoneType' object has no attribute 'moveBy'
```
